// Streams en vivo vía embed.st — proveedor real de lacancha.tv
// Patrón: https://embed.st/embed/admin/{match-slug}/{canal-num}
// Canal nums mapeados: FOX=1, FOX(SD)=2, BBC=3, BBC(SD)=4, Telemundo=5, Telemundo(SD)=6, TSN=7, TSN(SD)=8, ORF=9, ORF(SD)=10
const LIVE_SLUG = "ppv-iraq-vs-norway"; // Actualizar con el partido activo del día
const ES = (n) => `https://embed.st/embed/admin/${LIVE_SLUG}/${n}`;

const CHANNELS = [
  {
    id: "telemundo-1",
    name: "Telemundo",
    option: 1,
    icon: "📺",
    sub: "USA · Español",
    country: "US",
    free: true,
    desc: "Telemundo deportes en español — HD",
    embedUrl: ES(5),
  },
  {
    id: "telemundo-2",
    name: "Telemundo",
    option: 2,
    icon: "📺",
    sub: "USA · Español · SD",
    country: "US",
    free: true,
    desc: "Telemundo deportes en español — SD",
    embedUrl: ES(6),
  },
  {
    id: "fox-1",
    name: "FOX Sports",
    option: 1,
    icon: "📺",
    sub: "USA — HD",
    country: "US",
    free: true,
    desc: "FOX Sports cobertura deportiva — HD",
    embedUrl: ES(1),
  },
  {
    id: "fox-2",
    name: "FOX Sports",
    option: 2,
    icon: "📺",
    sub: "USA — SD",
    country: "US",
    free: true,
    desc: "FOX Sports cobertura deportiva — SD",
    embedUrl: ES(2),
  },
  {
    id: "bbc-1",
    name: "BBC One",
    option: 1,
    icon: "📺",
    sub: "Reino Unido — HD",
    country: "GB",
    free: true,
    desc: "BBC One cobertura deportiva — HD",
    embedUrl: ES(3),
  },
  {
    id: "bbc-2",
    name: "BBC One",
    option: 2,
    icon: "📺",
    sub: "Reino Unido — SD",
    country: "GB",
    free: true,
    desc: "BBC One cobertura deportiva — SD",
    embedUrl: ES(4),
  },
  {
    id: "tsn-1",
    name: "TSN",
    option: 1,
    icon: "📺",
    sub: "Canadá — HD",
    country: "CA",
    free: true,
    desc: "The Sports Network Canada — HD",
    embedUrl: ES(7),
  },
  {
    id: "tsn-2",
    name: "TSN",
    option: 2,
    icon: "📺",
    sub: "Canadá — SD",
    country: "CA",
    free: true,
    desc: "The Sports Network Canada — SD",
    embedUrl: ES(8),
  },
  {
    id: "orf-1",
    name: "ORF 1",
    option: 1,
    icon: "📺",
    sub: "Austria — HD",
    country: "AT",
    free: true,
    desc: "ORF 1 Austria deportes — HD",
    embedUrl: ES(9),
  },
  {
    id: "orf-2",
    name: "ORF 1",
    option: 2,
    icon: "📺",
    sub: "Austria — SD",
    country: "AT",
    free: true,
    desc: "ORF 1 Austria deportes — SD",
    embedUrl: ES(10),
  },
];

const MATCHES = [
  {
    id: 1,
    home: { name: "México",    flag: "🇲🇽", score: 2 },
    away: { name: "Brasil",    flag: "🇧🇷", score: 1 },
    status: "live", minute: 74,
    competition: "Copa del Mundo 2026",
    venue: "Estadio Azteca, México D.F.",
    channels: ["telemundo-1", "telemundo-2", "fox-1"],
  },
  {
    id: 2,
    home: { name: "Italia",    flag: "🇮🇹", score: 1 },
    away: { name: "Bélgica",   flag: "🇧🇪", score: 0 },
    status: "live", minute: 55,
    competition: "UEFA Nations League",
    venue: "San Siro, Milán",
    channels: ["bbc-1", "bbc-2", "tsn-1"],
  },
  {
    id: 3,
    home: { name: "Argentina", flag: "🇦🇷", score: null },
    away: { name: "Francia",   flag: "🇫🇷", score: null },
    status: "upcoming", time: "20:00",
    competition: "Copa del Mundo 2026 · Grupo C",
    venue: "MetLife Stadium, Nueva York",
    channels: ["telemundo-1", "telemundo-2", "fox-1", "fox-2"],
  },
  {
    id: 4,
    home: { name: "España",    flag: "🇪🇸", score: null },
    away: { name: "Alemania",  flag: "🇩🇪", score: null },
    status: "upcoming", time: "22:00",
    competition: "Copa del Mundo 2026 · Grupo B",
    venue: "Rose Bowl, Los Ángeles",
    channels: ["bbc-1", "bbc-2", "fox-1", "tsn-1"],
  },
  {
    id: 5,
    home: { name: "Portugal",  flag: "🇵🇹", score: null },
    away: { name: "Inglaterra",flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", score: null },
    status: "upcoming", time: "00:00",
    competition: "Copa del Mundo 2026 · Grupo D",
    venue: "AT&T Stadium, Dallas",
    channels: ["bbc-1", "tsn-1", "tsn-2", "fox-2"],
  },
  {
    id: 6,
    home: { name: "Colombia",  flag: "🇨🇴", score: null },
    away: { name: "Uruguay",   flag: "🇺🇾", score: null },
    status: "upcoming", time: "02:00",
    competition: "Copa del Mundo 2026 · Grupo A",
    venue: "SoFi Stadium, Los Ángeles",
    channels: ["telemundo-1", "orf-1", "fox-1"],
  },
  {
    id: 7,
    home: { name: "Marruecos", flag: "🇲🇦", score: null },
    away: { name: "Senegal",   flag: "🇸🇳", score: null },
    status: "upcoming", time: "04:00",
    competition: "Copa del Mundo 2026 · Grupo E",
    venue: "Levi's Stadium, San Francisco",
    channels: ["bbc-1", "bbc-2", "orf-1"],
  },
];

const RESULTS = [
  { home: { name: "América",   flag: "🦅", score: 3 }, away: { name: "Chivas",    flag: "⚽", score: 1 }, competition: "Liga MX · J17",          winner: "home" },
  { home: { name: "Barcelona", flag: "🔵", score: 0 }, away: { name: "R. Madrid", flag: "⚪", score: 2 }, competition: "LaLiga · J38",           winner: "away" },
  { home: { name: "Arsenal",   flag: "🔴", score: 2 }, away: { name: "Liverpool", flag: "🔴", score: 2 }, competition: "Premier League · GW38",  winner: "draw" },
  { home: { name: "Inter",     flag: "⚫", score: 1 }, away: { name: "PSG",       flag: "🔵", score: 0 }, competition: "Champions · Final",      winner: "home" },
];

const RANKING = [
  { pos: 1, name: "CristianR", pts: 33, avatar: "CR", color: "#f4a261", medal: "🏆" },
  { pos: 2, name: "MarcoG",    pts: 29, avatar: "MG", color: "#9ca3af", medal: "🥈" },
  { pos: 3, name: "LuisA",     pts: 27, avatar: "LA", color: "#cd7f32", medal: "🥉" },
  { pos: 4, name: "KarenP",    pts: 24, avatar: "KP", color: "#60a5fa" },
  { pos: 5, name: "DiegoR",    pts: 21, avatar: "DR", color: "#c084fc" },
  { pos: 6, name: "SofiaV",    pts: 19, avatar: "SV", color: "#f87171" },
  { pos: 7, name: "JuanC",     pts: 17, avatar: "JC", color: "#34d399" },
  { pos: 8, name: "AnaM",      pts: 15, avatar: "AM", color: "#fb923c" },
];

const TRIVIA = [
  "<strong>Brasil</strong> es la única selección en haber participado en <strong>todos</strong> los mundiales. Ha ganado <strong>5 títulos</strong>: 1958, 1962, 1970, 1994 y 2002.",
  "El estadio <strong>Azteca</strong> en México D.F. es el único que ha albergado <strong>dos finales</strong> de Copa del Mundo: 1970 y 1986.",
  "<strong>Pelé</strong> sigue siendo el único jugador en ganar <strong>tres Copas del Mundo</strong> (1958, 1962 y 1970).",
  "El gol más rápido en historia mundialista lo marcó <strong>Hakan Şükür</strong> de Turquía en solo <strong>11 segundos</strong> en 2002.",
  "La Copa del Mundo <strong>2026</strong> será la primera en realizarse en <strong>tres países</strong>: México, Estados Unidos y Canadá.",
  "<strong>Lionel Messi</strong> es el máximo goleador en la historia del Mundial con <strong>13 goles</strong>, superando a Klose en 2022.",
];
