// Streams en vivo vía embed.st — proveedor real de lacancha.tv
// Patrón: https://embed.st/embed/admin/{match-slug}/{canal-num}
// Canal nums mapeados: FOX=1, FOX(SD)=2, BBC=3, BBC(SD)=4, Telemundo=5, Telemundo(SD)=6, TSN=7, TSN(SD)=8, ORF=9, ORF(SD)=10
const LIVE_SLUG = "ppv-iraq-vs-norway"; // Actualizar con el partido activo del día
const ES = (n) => `https://embed.st/embed/admin/${LIVE_SLUG}/${n}`;

const CHANNELS = [
  {
    id: "telemundo-1",
    name: "Telemundo",
    option: 1,
    icon: "📺",
    sub: "USA · Español",
    country: "US",
    free: true,
    desc: "Telemundo deportes en español — HD",
    embedUrl: ES(5),
  },
  {
    id: "telemundo-2",
    name: "Telemundo",
    option: 2,
    icon: "📺",
    sub: "USA · Español · SD",
    country: "US",
    free: true,
    desc: "Telemundo deportes en español — SD",
    embedUrl: ES(6),
  },
  {
    id: "fox-1",
    name: "FOX Sports",
    option: 1,
    icon: "📺",
    sub: "USA — HD",
    country: "US",
    free: true,
    desc: "FOX Sports cobertura deportiva — HD",
    embedUrl: ES(1),
  },
  {
    id: "fox-2",
    name: "FOX Sports",
    option: 2,
    icon: "📺",
    sub: "USA — SD",
    country: "US",
    free: true,
    desc: "FOX Sports cobertura deportiva — SD",
    embedUrl: ES(2),
  },
  {
    id: "bbc-1",
    name: "BBC One",
    option: 1,
    icon: "📺",
    sub: "Reino Unido — HD",
    country: "GB",
    free: true,
    desc: "BBC One cobertura deportiva — HD",
    embedUrl: ES(3),
  },
  {
    id: "bbc-2",
    name: "BBC One",
    option: 2,
    icon: "📺",
    sub: "Reino Unido — SD",
    country: "GB",
    free: true,
    desc: "BBC One cobertura deportiva — SD",
    embedUrl: ES(4),
  },
  {
    id: "tsn-1",
    name: "TSN",
    option: 1,
    icon: "📺",
    sub: "Canadá — HD",
    country: "CA",
    free: true,
    desc: "The Sports Network Canada — HD",
    embedUrl: ES(7),
  },
  {
    id: "tsn-2",
    name: "TSN",
    option: 2,
    icon: "📺",
    sub: "Canadá — SD",
    country: "CA",
    free: true,
    desc: "The Sports Network Canada — SD",
    embedUrl: ES(8),
  },
  {
    id: "orf-1",
    name: "ORF 1",
    option: 1,
    icon: "📺",
    sub: "Austria — HD",
    country: "AT",
    free: true,
    desc: "ORF 1 Austria deportes — HD",
    embedUrl: ES(9),
  },
  {
    id: "orf-2",
    name: "ORF 1",
    option: 2,
    icon: "📺",
    sub: "Austria — SD",
    country: "AT",
    free: true,
    desc: "ORF 1 Austria deportes — SD",
    embedUrl: ES(10),
  },
];

// Partidos reales del Mundial 2026 — fuente: lacancha.tv/es/calendario
const MATCHES = [
  // ── EN VIVO ──
  {
    id: 1,
    home: { name: "Irak",     flag: "🇮🇶", score: 0 },
    away: { name: "Noruega",  flag: "🇳🇴", score: 0 },
    status: "live", minute: 42,
    competition: "Copa del Mundo 2026 · Fase de Grupos",
    venue: "Estadio Azteca · Mexico City",
    channels: ["telemundo-1", "telemundo-2", "fox-1", "fox-2", "bbc-1", "tsn-1"],
  },
  // ── PRÓXIMOS HOY ──
  {
    id: 2,
    home: { name: "Argentina", flag: "🇦🇷", score: null },
    away: { name: "Argelia",   flag: "🇩🇿", score: null },
    status: "upcoming", time: "01:00",
    competition: "Copa del Mundo 2026 · Jornada 2",
    venue: "Arrowhead Stadium · Kansas City",
    channels: ["telemundo-1", "telemundo-2", "fox-1"],
  },
  {
    id: 3,
    home: { name: "Portugal",  flag: "🇵🇹", score: null },
    away: { name: "R.D. Congo",flag: "🇨🇩", score: null },
    status: "upcoming", time: "17:00",
    competition: "Copa del Mundo 2026 · Jornada 2",
    venue: "NRG Stadium · Houston",
    channels: ["fox-1", "fox-2", "bbc-1", "orf-1"],
  },
  {
    id: 4,
    home: { name: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", score: null },
    away: { name: "Croacia",    flag: "🇭🇷", score: null },
    status: "upcoming", time: "20:00",
    competition: "Copa del Mundo 2026 · Jornada 2",
    venue: "AT&T Stadium · Dallas",
    channels: ["bbc-1", "bbc-2", "tsn-1", "tsn-2"],
  },
  {
    id: 5,
    home: { name: "Uzbekistán", flag: "🇺🇿", score: null },
    away: { name: "Colombia",   flag: "🇨🇴", score: null },
    status: "upcoming", time: "02:00",
    competition: "Copa del Mundo 2026 · Jornada 2",
    venue: "Estadio Azteca · Mexico City",
    channels: ["telemundo-1", "telemundo-2", "fox-1", "orf-1"],
  },
  {
    id: 6,
    home: { name: "México",    flag: "🇲🇽", score: null },
    away: { name: "Corea",     flag: "🇰🇷", score: null },
    status: "upcoming", time: "01:00",
    competition: "Copa del Mundo 2026 · Jornada 2",
    venue: "Estadio Akron · Guadalajara",
    channels: ["telemundo-1", "telemundo-2", "fox-1", "fox-2"],
  },
  {
    id: 7,
    home: { name: "Brasil",    flag: "🇧🇷", score: null },
    away: { name: "Haití",     flag: "🇭🇹", score: null },
    status: "upcoming", time: "00:30",
    competition: "Copa del Mundo 2026 · Jornada 2",
    venue: "Lincoln Financial Field · Philadelphia",
    channels: ["telemundo-1", "bbc-1", "orf-1"],
  },
  {
    id: 8,
    home: { name: "Alemania",  flag: "🇩🇪", score: null },
    away: { name: "Costa de Marfil", flag: "🇨🇮", score: null },
    status: "upcoming", time: "20:00",
    competition: "Copa del Mundo 2026 · Jornada 2",
    venue: "BMO Field · Toronto",
    channels: ["fox-1", "fox-2", "bbc-1", "bbc-2", "tsn-1"],
  },
  {
    id: 9,
    home: { name: "España",    flag: "🇪🇸", score: null },
    away: { name: "Arabia Saudita", flag: "🇸🇦", score: null },
    status: "upcoming", time: "16:00",
    competition: "Copa del Mundo 2026 · Jornada 2",
    venue: "Mercedes-Benz Stadium · Atlanta",
    channels: ["bbc-1", "bbc-2", "fox-1", "orf-1"],
  },
  {
    id: 10,
    home: { name: "Francia",   flag: "🇫🇷", score: null },
    away: { name: "Irak",      flag: "🇮🇶", score: null },
    status: "upcoming", time: "21:00",
    competition: "Copa del Mundo 2026 · Jornada 2",
    venue: "Lincoln Financial Field · Philadelphia",
    channels: ["telemundo-1", "bbc-1", "fox-1", "fox-2"],
  },
];

// Resultados reales Jornada 1 — Copa del Mundo 2026
const RESULTS = [
  { home: { name: "México",       flag: "🇲🇽", score: 2 }, away: { name: "Sudáfrica",   flag: "🇿🇦", score: 0 }, competition: "Copa del Mundo 2026 · J1", winner: "home" },
  { home: { name: "Alemania",     flag: "🇩🇪", score: 7 }, away: { name: "Curazao",     flag: "🇨🇼", score: 1 }, competition: "Copa del Mundo 2026 · J1", winner: "home" },
  { home: { name: "Francia",      flag: "🇫🇷", score: 3 }, away: { name: "Senegal",     flag: "🇸🇳", score: 1 }, competition: "Copa del Mundo 2026 · J1", winner: "home" },
  { home: { name: "Brasil",       flag: "🇧🇷", score: 1 }, away: { name: "Marruecos",   flag: "🇲🇦", score: 1 }, competition: "Copa del Mundo 2026 · J1", winner: "draw" },
  { home: { name: "EE.UU.",       flag: "🇺🇸", score: 4 }, away: { name: "Paraguay",    flag: "🇵🇾", score: 1 }, competition: "Copa del Mundo 2026 · J1", winner: "home" },
  { home: { name: "España",       flag: "🇪🇸", score: 0 }, away: { name: "Cabo Verde",  flag: "🇨🇻", score: 0 }, competition: "Copa del Mundo 2026 · J1", winner: "draw" },
  { home: { name: "Países Bajos", flag: "🇳🇱", score: 2 }, away: { name: "Japón",       flag: "🇯🇵", score: 2 }, competition: "Copa del Mundo 2026 · J1", winner: "draw" },
  { home: { name: "Arabia Saudita",flag:"🇸🇦", score: 1 }, away: { name: "Uruguay",     flag: "🇺🇾", score: 1 }, competition: "Copa del Mundo 2026 · J1", winner: "draw" },
  { home: { name: "Suecia",       flag: "🇸🇪", score: 5 }, away: { name: "Túnez",       flag: "🇹🇳", score: 1 }, competition: "Copa del Mundo 2026 · J1", winner: "home" },
  { home: { name: "Australia",    flag: "🇦🇺", score: 2 }, away: { name: "Turquía",     flag: "🇹🇷", score: 0 }, competition: "Copa del Mundo 2026 · J1", winner: "home" },
  { home: { name: "Costa de Marfil", flag: "🇨🇮", score: 1 }, away: { name: "Ecuador", flag: "🇪🇨", score: 0 }, competition: "Copa del Mundo 2026 · J1", winner: "home" },
  { home: { name: "Canadá",       flag: "🇨🇦", score: 1 }, away: { name: "Bosnia",      flag: "🇧🇦", score: 1 }, competition: "Copa del Mundo 2026 · J1", winner: "draw" },
];

const RANKING = [
  { pos: 1, name: "CristianR", pts: 33, avatar: "CR", color: "#f4a261", medal: "🏆" },
  { pos: 2, name: "MarcoG",    pts: 29, avatar: "MG", color: "#9ca3af", medal: "🥈" },
  { pos: 3, name: "LuisA",     pts: 27, avatar: "LA", color: "#cd7f32", medal: "🥉" },
  { pos: 4, name: "KarenP",    pts: 24, avatar: "KP", color: "#60a5fa" },
  { pos: 5, name: "DiegoR",    pts: 21, avatar: "DR", color: "#c084fc" },
  { pos: 6, name: "SofiaV",    pts: 19, avatar: "SV", color: "#f87171" },
  { pos: 7, name: "JuanC",     pts: 17, avatar: "JC", color: "#34d399" },
  { pos: 8, name: "AnaM",      pts: 15, avatar: "AM", color: "#fb923c" },
];

const TRIVIA = [
  "El Mundial 2026 se juega en <strong>tres países</strong>: México, Estados Unidos y Canadá — el primero en la historia en hacerlo. Participa un récord de <strong>48 selecciones</strong>.",
  "<strong>México</strong> ganó su partido inaugural 2–0 ante Sudáfrica en el <strong>Estadio Azteca</strong>, con el estadio lleno a su máxima capacidad.",
  "<strong>Alemania</strong> marcó 7 goles a Curazao en el arranque del torneo — la mayor goleada de la Jornada 1 del Mundial 2026.",
  "El <strong>Estadio Azteca</strong> alberga partidos por tercera Copa del Mundo consecutiva (1970, 1986 y 2026), un récord único en la historia del torneo.",
  "<strong>EE.UU.</strong> arrancó con una aplastante victoria 4–1 sobre Paraguay, demostrando su potencial como anfitrión y favorito en casa.",
  "El Mundial 2026 es el primero con <strong>Grupo de 3 equipos</strong> — los dos primeros de cada grupo y los 8 mejores terceros avanzan a octavos de final.",
];
